### ISSUE TITLE
Error after install magento 2 rc with sample data

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2-sample-data#10]
sytems.log

[2015-11-07 03:38:28] main.CRITICAL: 
Compilation from source: 
frontend/Magento/luma/en_US/css/email.less
variable @modal-slide-header__padding-vertical is undefined in file D:/App/htdocs/magentodev/var/view_preprocessed/css/frontend/Magento/luma/en_US/css/source/_theme.less in _theme.less on line 254, column 37
252| // Modal popup
253| @modal-action-close__font-size: @font-size__base;
254| @modal-slide-action-close__padding: @modal-slide-header__padding-vertical @modal-popup__padding;
255| 
256| // Checkout tooltip icon
257| @checkout-tooltip-icon__font-size: 21px;
[] []
[2015-11-07 03:38:29] main.CRITICAL: 
Compilation from source: 
frontend/Magento/luma/en_US/css/email-inline.less
variable @modal-slide-header__padding-vertical is undefined in file D:/App/htdocs/magentodev/var/view_preprocessed/css/frontend/Magento/luma/en_US/css/source/_theme.less in _theme.less on line 254, column 37
252| // Modal popup
253| @modal-action-close__font-size: @font-size__base;
254| @modal-slide-action-close__padding: @modal-slide-header__padding-vertical @modal-popup__padding;
255| 
256| // Checkout tooltip icon
257| @checkout-tooltip-icon__font-size: 21px;
[] []
[2015-11-07 03:42:39] main.ERROR: Sample Data error: Error in data structure: entity values are mixed [] []
[2015-11-07 03:43:25] main.ERROR: Sample Data error: Notice: Undefined index: Black
in D:\App\htdocs\magento2-sample-data\app\code\Magento\SwatchesSampleData\Model\Swatches.php on line 131 [] []

**Comment by voleye** [comment]
Hi @minhluan259, sorry for late answer!

I have tried to install Sample Data on a latest version of Magento and Sample Data and can`t reproduce the issue. 

Could you please try to use latest version and describe more details if the issue still valid?

**Comment by minhluan259** [comment]
With Sample Data latest version, the issue resolved. Thank @voleye.
