### ISSUE TITLE
Installing magento/sample-data-media (100.0.2)

### ISSUE THREAD

**Issue by przmak** [magento/magento2-sample-data#11]
The steps that I do:
1.Clone mage2 project
2.Switch to master
From Root folder
3.composer install
4.php bin/magento sampledata:deploy

And I get a boom
![image](https://cloud.githubusercontent.com/assets/4508852/11224074/764057e6-8d73-11e5-9988-3ce72526c5f7.png)

Soft that I have:
Xampp 5.6.14
It has apache 2.4 and php 5.6.14 
About mysql, read it evloved into mariaDB thou the mysql command is on, anyway I don't have any problem with normal installation of magento2,

Composer:
Composer version 1.0-dev (a066171dcc023ad6429881a7692e46f10e080f99) 2015-11-12 13:44:17

Any tips what I'm doing wrong or what is the problem :v

**Comment by voleye** [comment]
Hi @przmak,

From the screen shot I can see that it tries to download the packages from "packages.magento.com".
In latest version it was changed from "packages.magento.com" to "repo.magento.com".

Could you please try to use latest version of Magento and Sample Data?
Please let us know is it helps to solve the issue.

**Comment by minhluan259** [comment]
@przmak clear cache with command "composer clearcache", and trying install with latest version

**Comment by przmak** [comment]
Anyway I downloaded the zip archive and everything works fine :P But, I have still problems with the instalation of samples via cloning the repo -> master -> composer install -> samplepackage:deploy
and even after chaning the url, and downloading new project that has already setted new repo url properly, the same problem occurs, with the checksum verification

**Comment by ghost** [comment]
@przmak I tried the same steps you did and got a different error. 

```
[Composer\Downloader\TransportException]
  The 'https://repo.magento.com/packages.json' URL required authentication.
  You must be using the interactive console to authenticate
```

The reason for this error is that we're suppressing Composer messages in the sampledata:deploy command. To resolve it, just run `composer update` from the Magento root dir. I then installed Magento and checked everything, seems to work

Your checksum error must have a different cause but if you try what I suggest, it will work.

**Comment by przmak** [comment]
Hey guys, I was managed to fix the issue, the problem lied in my wifi, each time I tried to download a ziped archive from https://www.magentocommerce.com/download it ended up in a failure for exmaple. after some time once it downloaded 30mb or 5mb and then the download stopped thou my Internet connection was fine, no package drops etc. I assume that my problem with php bin/magento sampledata:deploy and the sample-data-media had the same nature. 
After I changed my Internet from WIFI to cabel everything started to work :)

**Comment by MuneebMagenticians** [comment]
Did you have clear the cache of your Magento 2 store? If not then first clear it. Then run these commands in your store's root directory:

php bin/magento sampledata:deploy
php bin/magento setup:upgrade

To know in more detail, you can refer to this guide:  [How to Install Magento 2 Sample Data](https://magenticians.com/install-magento-2-sample-data/)
