### ISSUE TITLE
Sample data return error Setup version for module 'Magento_CustomerSampleData' is not specified

### ISSUE THREAD

**Issue by belovanton** [magento/magento2-sample-data#14]
This is what I was do.
cd /var/www/magento/current
rm -rf /var/www/magento/current/.*
rm -rf /var/www/magento/current/*
git clone https://github.com/magento/magento2.git ./
git checkout develop
find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento
composer config repositories.magento composer http://packages.magento.com 
composer install
mysql -uroot -ptmp -h mysql -e "DROP DATABASE magento2; CREATE DATABASE magento2;";
php -d xdebug.max_nesting_level=500 -f bin/magento setup:install --base-url="http://magento2.hostname/" --backend-frontname=admin --db-host=mysql --db-name="magento2" --db-user="root" --db-password="tmp" --admin-firstname=Local --admin-lastname=Admin --admin-email=admin@example.com --admin-user="admin" --admin-password="123123aa" --language=en_US --currency=USD --timezone=America/Chicago
rm -rf ~/sample-data
git clone https://github.com/magento/magento2-sample-data.git ~/sample-data
git checkout develop
cd ~/sample-data/dev/tools
php build-sample-data.php --ce-source="/var/www/magento/current"
cd /var/www/magento/current
php -d xdebug.max_nesting_level=500 bin/magento setup:upgrade
bin/magento setup:di:compile
chown -R www-data:www-data ./*

This is what I get when its finish:
cat var/report/873018421313 
a:4:{i:0;s:70:"Setup version for module 'Magento_CustomerSampleData' is not specified";i:1;s:3320:"#0 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Module/DbVersionInfo.php(56): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Magento_Custome...', '2.0.0')
#1 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Module/DbVersionInfo.php(79): Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate('Magento_Custome...')
#2 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(55): Magento\Framework\Module\DbVersionInfo->getDbVersionErrors()
#3 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#5 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#6 /var/www/magento/2016-02-09-10-43/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#7 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#9 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#10 /var/www/magento/2016-02-09-10-43/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#11 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#13 /var/www/magento/2016-02-09-10-43/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/magento/2016-02-09-10-43/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#16 /var/www/magento/2016-02-09-10-43/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#17 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}

**Comment by ghost** [comment]
I just have a couple of misc. comments:
- You don't have to manually drop and re-create the database; add the `--cleanup-database` optional parameter to the CLI installer and it will do that for you.
-  You're not using recommended ownership; we recommend another user besides the web server user own the files. This could be specific to your implementation though

I'm not sure the cause of your error, sorry. Last time I tried it it worked. I'm told it should work if you get both `develop` branches though. As an experiment, you can try getting a release/tag for both repos.

**Comment by belovanton** [comment]
Ok, thx.
This is magento build log https://dpaste.de/tA21

**Comment by belovanton** [comment]
issue was in symlink path and files permissions
