### ISSUE TITLE
Stylesheet 404 when using pub directory as DocumentRoot

### ISSUE THREAD

**Issue by davidalger** [magento/magento2-sample-data#2]
When Magento 2 is installed using the `pub` folder as the DocumentRoot, the stylesheet which is configured by the sample data installer fails to load. Manually changing the `design/head/includes` config to drop `/pub` from the URI resolves the problem, but the install process should not setup sample data in a which does not work in a supported deployment scenario.

**Comment by voleye** [comment]
Thank you for reporting @davidalger, we have created MAGETWO-43084 to track a fix for this.

**Comment by voleye** [comment]
Fixed, closed this issue
