### ISSUE TITLE
No license.txt

### ISSUE THREAD

**Issue by tomispepe** [magento/magento2-sample-data#4]
What license agreement is intended to be associated with the sample data?  If I want to use the sample data included in this repository to demo a module or theme can I do so legally?

"Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend."
\-[GitHub Help > Open source licensing](https://help.github.com/articles/open-source-licensing/)

**Comment by voleye** [comment]
Hi @tomispepe , thank you for helping us make Magento better!

We have created MAGETWO-44617 to track a fix for this.

**Comment by voleye** [comment]
Fixed, closed this issue
