### ISSUE TITLE
Configurable Product Installation failed

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2-sample-data#5]
While installing Magento2 according to this instruction: http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data.html
I get the following error:
```PHP Fatal error:  Undefined class constant 'FIELD_NAME_VALIDATION_STRATEGY' in /private/var/www/magento/magento2-sample-data/app/code/Magento/SampleData/Module/ConfigurableProduct/Setup/Product.php on line 84```

Both magento2 and sample-data repositories on master.

**Comment by xcomSteveJohnson** [comment]
Do you see any errors about insufficient privileges?

**Comment by rtull** [comment]
Having the same issue here. We had the whole codebase set to 777 because it's a local environment so I doubt it was a permissions issue in my case.

**Comment by rtull** [comment]
After a little digging internally here at Classy Llama, looks like one of our team members has already submitted a fix: https://github.com/magento/magento2-sample-data/pull/3

This fix isn't in the master branch as of yet but can be manually applied to work around the issue for now.

**Comment by davidalger** [comment]
Note: I don't see this issue when running through the sample data installer using the merchant_beta branch from both the magneto2 and magento2-sample-data repo. Might try that.

**Comment by voleye** [comment]
Hi @sydekumf 

Please, use the following map of "Sample Data" availability:

Stable version available through
 - Composer (packages.magento.com version 1.0.0-beta5)
 - VCS (https://github.com/magento/magento2-sample-data, branch "merchant_beta")

Develop version available through
 - VCS (https://github.com/magento/magento2-sample-data, branch "develop")

**Comment by voleye** [comment]
Fixed in 2.0.0-rc, closed this issue
