### ISSUE TITLE
Error during sample data installation: Undefined index: black

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2-sample-data#7]
Hi, I am trying to install merchant_beta 1.0.0-beta6 sample-data into merchant_beta 1.0.0-beta6 of magento2.

I run 
`php -f build-sample-data.php -- --ce-source="/somePath/magento2"`
to deploy the sample-data and then run
`composer install`
in the magento2 directory.

Then I install magento2 with the following command line:

`php bin/magento setup:install --base-url=http://m2-local.dev.example.com/ --base-url-secure=https://m2-local.dev.example.com/ --db-host=localhost --db-name=magento2_merchant_beta --db-user=sa --db-password=examplePW123456 --admin-firstname=Magento --admin-lastname=User --admin-email=example@example.com --admin-user=admin --admin-password=admin123 --backend-frontname=admin --language=en_US --currency=CHF --timezone=Europe/Zurich --use-sample-data --use-rewrites=1 --use-secure=1 --use-secure-admin=1 --cleanup-database`

But during the installation, the following error occurs:

[Progress: 285 / 288]
Installing sample data:
Installing theme:
.
Installing customers:
.
Installing CMS pages:
....
Installing catalog attributes:
...........................
Installing categories:
.........................................
Installing simple products:
............................................
Installing bundle products:
.
Installing downloadable products:
......
Installing grouped products:
.
Installing configurable products:

  [Magento\Setup\SampleDataException]
  Error during sample data installation: Undefined index: black

What can I do?

Thanks for your help.

**Comment by xcomSteveJohnson** [comment]
This is a guess. You should run `composer install `before you run `build-sample-data`. I don't know if that's the issue you're having but `build-sample-data` creates symbolic links to CE that might not work.

There is a different error if you try to install sample data from the `master` branch. I have not tried it from one of the `merchant_beta` branches. What branch are you using?

**Comment by bh-ref** [comment]
I am using the merchant_beta branch for both, magento2 and the sample-data as well.

Running composer install` before build-sample-data fixed the problem.

Thanks for your help! :)

**Comment by xcomSteveJohnson** [comment]
Great, glad we could help.
