### ISSUE TITLE
Orders importing failed

### ISSUE THREAD

**Issue by kuafucode** [magento/magento2-sample-data#8]
It failed with both master and merchant_beta sample data branch, for magento2 master branch. didn't try dev branch.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vat_id' in 'field list', query was:
   INSERT INTO `quote_address` (`quote_id`, `customer_id`, `save_in_address_book`, `customer_
  address_id`, `address_type`, `email`, `prefix`, `firstname`, `middlename`, `lastname`, `suf
  fix`, `company`, `street`, `city`, `region`, `region_id`, `postcode`, `country_id`, `teleph
  one`, `fax`, `same_as_billing`, `collect_shipping_rates`, `shipping_method`, `shipping_desc
  ription`, `weight`, `subtotal`, `base_subtotal`, `tax_amount`, `base_tax_amount`, `shipping
  _amount`, `base_shipping_amount`, `shipping_tax_amount`, `base_shipping_tax_amount`, `disco
  unt_amount`, `base_discount_amount`, `grand_total`, `base_grand_total`, `applied_taxes`, `d
  iscount_description`, `shipping_discount_amount`, `base_shipping_discount_amount`, `subtota
  l_incl_tax`, `discount_tax_compensation_amount`, `base_discount_tax_compensation_amount`, `
  shipping_discount_tax_compensation_amount`, `shipping_incl_tax`, `base_shipping_incl_tax`,
  `free_shipping`, `vat_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
   ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

**Comment by voleye** [comment]
Hi @kuafucode, Sample Data "master" branch was updated yesterday as well as Magento "master" brunch.

Could you please try to reinstall magento from scratch (clean db, "var" and "pub/static" folders)?
