### ISSUE TITLE
Installation using composer breaks with magento2 latest develp version

### ISSUE THREAD

**Issue by degaray** [magento/magento2-sample-data#9]
I am trying to install this sample data using the 'bin/magento sampledata:deploy' command and it breaks because it says the requirements cannot be fulfilled. This is the log I get:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/module-msrp-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package magento/module-catalog-rule-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package magento/module-offline-shipping-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package magento/module-grouped-product-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package magento/module-bundle-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package magento/module-sales-rule-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package magento/module-configurable-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package magento/module-product-links-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package magento/module-widget-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 10
    - The requested package magento/module-cms-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 11
    - The requested package magento/module-theme-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 12
    - The requested package magento/module-review-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 13
    - The requested package magento/module-customer-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 14
    - The requested package magento/module-tax-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 15
    - The requested package magento/module-downloadable-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 16
    - The requested package magento/module-wishlist-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 17
    - The requested package magento/module-swatches-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 18
    - The requested package magento/module-catalog-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 19
    - The requested package magento/module-sales-sample-data could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by xcomSteveJohnson** [comment]
At this time, you cannot use that command to install sample data. The only way that works (AFAIK) is to clone the develop branches of the Magento GitHub repo and the sample data repo and use this: http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-sample-data.html

**Comment by voleye** [comment]
Hi @degaray, sample data packages have already been published at https://packages.magento.com
so, now it should works.

Please, try again to use the command bin/magento sampledata:deploy and let us know if you have any problems with this

**Comment by xcomSteveJohnson** [comment]
@degaray Yes, I learned this after I made my comment. Sorry for any confusion it might have caused.
